server:
  port: 8080

spring:
  application:
    name: bff-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: inventory-products
          uri: http://inventory-service:8082
          predicates:
            - Path=/products/**

        - id: inventory-categories
          uri: http://inventory-service:8082
          predicates:
            - Path=/categories/**

        - id: inventory-movements
          uri: http://inventory-service:8082
          predicates:
            - Path=/movements/**

        - id: inventory-clients
          uri: http://inventory-service:8082
          predicates:
            - Path=/clients/**

        - id: auth-users
          uri: http://auth-service:8081
          predicates:
            - Path=/users/**

        - id: inventory-orders
          uri: http://inventory-service:8082
          predicates:
            - Path=/orders/**

        - id: inventory-order-details
          uri: http://inventory-service:8082
          predicates:
            - Path=/order-details/**

        - id: inventory-dispatches
          uri: http://inventory-service:8082
          predicates:
            - Path=/dispatches/**

        - id: inventory-deliveries
          uri: http://inventory-service:8082
          predicates:
            - Path=/deliveries/**

