server:
  port: 8080

spring:
  application:
    name: bff-gateway

  cloud:
    gateway:

      routes:

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: inventory-products
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

        - id: inventory-categories
          uri: http://localhost:8082
          predicates:
            - Path=/categories/**

        - id: inventory-movements
          uri: http://localhost:8082
          predicates:
            - Path=/movements/**

        - id: inventory-clients
          uri: http://localhost:8082
          predicates:
            - Path=/clients/**

        - id: auth-users
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: inventory-orders
          uri: http://localhost:8082
          predicates:
          - Path=/orders/**