server:
  port: 8081

spring:

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgres:5432/inventorydb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  jackson:
    time-zone: America/Santiago

jwt:
  secret: inventario-secreto-super-largo-para-jwt